"""empty message

Revision ID: 389b6ef8af0a
Revises: f5e4158b2a08
Create Date: 2021-06-13 22:39:57.945830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389b6ef8af0a'
down_revision = 'f5e4158b2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_data', sa.Column('request_date', sa.Date(), nullable=False))
    op.add_column('verification_data', sa.Column('verification_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_data', 'verification_date')
    op.drop_column('verification_data', 'request_date')
    # ### end Alembic commands ###
